
export const CATEGORY_ACTION_TYPES = {
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAIL: 'FETCH_CATEGORIES_FAIL',
}

